apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-monorepo-app
  labels:
    app: java-monorepo-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-monorepo-app
  template:
    metadata:
      labels:
        app: java-monorepo-app
        version: v1
    spec:
      containers:
      - name: java-app
        image: java-monorepo-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "ps aux | grep java | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "ps aux | grep java | grep -v grep"
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always 