apiVersion: v1
kind: Service
metadata:
  name: java-monorepo-service
  labels:
    app: java-monorepo-app
spec:
  selector:
    app: java-monorepo-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 